using System;

namespace UAssetAPI.UnrealTypes.Enums
{
    /// <summary>
    /// Flags describing a class.
    /// </summary>
    [Flags]
    public enum EClassFlags : uint
    {
        /// <summary>No Flags</summary>
        CLASS_None = 0x00000000,
        /// <summary>Class is abstract and can't be instantiated directly.</summary>
        CLASS_Abstract = 0x00000001,
        /// <summary>Save object configuration only to Default INIs, never to local INIs. Must be combined with CLASS_Config</summary>
        CLASS_DefaultConfig = 0x00000002,
        /// <summary>Load object configuration at construction time.</summary>
        CLASS_Config = 0x00000004,
        /// <summary>This object type can't be saved; null it out at save time.</summary>
        CLASS_Transient = 0x00000008,
        /// <summary>Successfully parsed.</summary>
        CLASS_Parsed = 0x00000010,
        /// <summary>???</summary>
        CLASS_MatchedSerializers = 0x00000020,
        /// <summary>Indicates that the config settings for this class will be saved to Project/User*.ini (similar to CLASS_GlobalUserConfig)</summary>
        CLASS_ProjectUserConfig = 0x00000040,
        /// <summary>Class is a native class - native interfaces will have CLASS_Native set, but not RF_MarkAsNative</summary>
        CLASS_Native = 0x00000080,
        /// <summary>Don't export to C++ header.</summary>
        CLASS_NoExport = 0x00000100,
        /// <summary>Do not allow users to create in the editor.</summary>
        CLASS_NotPlaceable = 0x00000200,
        /// <summary>Handle object configuration on a per-object basis, rather than per-class.</summary>
        CLASS_PerObjectConfig = 0x00000400,
        /// <summary>Whether SetUpRuntimeReplicationData still needs to be called for this class</summary>
        CLASS_ReplicationDataIsSetUp = 0x00000800u,
        /// <summary>Class can be constructed from editinline New button.</summary>
        CLASS_EditInlineNew = 0x00001000,
        /// <summary>Display properties in the editor without using categories.</summary>
        CLASS_CollapseCategories = 0x00002000,
        /// <summary>Class is an interface</summary>
        CLASS_Interface = 0x00004000,
        /// <summary>Do not export a constructor for this class, assuming it is in the cpptext</summary>
        CLASS_CustomConstructor = 0x00008000,
        /// <summary>All properties and functions in this class are const and should be exported as const</summary>
        CLASS_Const = 0x00010000,
        /// <summary>Class flag indicating the class is having its layout changed, and therefore is not ready for a CDO to be created</summary>
        CLASS_LayoutChanging = 0x00020000,
        /// <summary>Indicates that the class was created from blueprint source material</summary>
        CLASS_CompiledFromBlueprint = 0x00040000,
        /// <summary>Indicates that only the bare minimum bits of this class should be DLL exported/imported</summary>
        CLASS_MinimalAPI = 0x00080000,
        /// <summary>Indicates this class must be DLL exported/imported (along with all of it's members)</summary>
        CLASS_RequiredAPI = 0x00100000,
        /// <summary>Indicates that references to this class default to instanced. Used to be subclasses of UComponent, but now can be any UObject</summary>
        CLASS_DefaultToInstanced = 0x00200000,
        /// <summary>Indicates that the parent token stream has been merged with ours.</summary>
        CLASS_TokenStreamAssembled = 0x00400000,
        /// <summary>Class has component properties.</summary>
        CLASS_HasInstancedReference = 0x00800000,
        /// <summary>Don't show this class in the editor class browser or edit inline new menus.</summary>
        CLASS_Hidden = 0x01000000,
        /// <summary>Don't save objects of this class when serializing</summary>
        CLASS_Deprecated = 0x02000000,
        /// <summary>Class not shown in editor drop down for class selection</summary>
        CLASS_HideDropDown = 0x04000000,
        /// <summary>Class settings are saved to AppData/..../Blah.ini (as opposed to CLASS_DefaultConfig)</summary>
        CLASS_GlobalUserConfig = 0x08000000,
        /// <summary>Class was declared directly in C++ and has no boilerplate generated by UnrealHeaderTool</summary>
        CLASS_Intrinsic = 0x10000000,
        /// <summary>Class has already been constructed (maybe in a previous DLL version before hot-reload).</summary>
        CLASS_Constructed = 0x20000000,
        /// <summary>Indicates that object configuration will not check against ini base/defaults when serialized</summary>
        CLASS_ConfigDoNotCheckDefaults = 0x40000000,
        /// <summary>Class has been consigned to oblivion as part of a blueprint recompile, and a newer version currently exists.</summary>
        CLASS_NewerVersionExists = 0x80000000,
    };
}
